name: testing_binder
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - setuptools
  - matplotlib
  - numpy
  - scipy
  - pandas
  - bokeh
  - jupyterlab<1.0
  - pip:
    -  jupyterlab_latex<1.0